version: '3.8'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: quotes_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123456

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 quotes_site.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
